# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NerCBAaamchas93Z4liPwVk1ZkVxKXcx

Part 1 : Auto MPG Regression
Predict fuel efficiency (mpg) using Linear Regression and Decision Tree. Pipeline-based approach with model export for Streamlit deployment.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.neighbors import KNeighborsRegressor
import joblib

import warnings
warnings.filterwarnings('ignore')

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
col_names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
             'acceleration', 'model_year', 'origin', 'car_name']

df = pd.read_csv(url, sep='\s+', names=col_names, na_values='?')
df.drop(columns=['car_name'], inplace=True)  # not useful for regression
print(df.shape)
df.head()

df.describe()

print("Missing values:")
print(df.isnull().sum())

# Distribution of target variable
plt.figure(figsize=(6, 4))
df['mpg'].hist(bins=20, color='steelblue', edgecolor='white')
plt.title('MPG Distribution')
plt.xlabel('mpg')
plt.ylabel('count')
plt.tight_layout()
plt.show()

# Correlation heatmap
plt.figure(figsize=(7, 5))
sns.heatmap(df.corr(), annot=True, fmt='.2f', cmap='coolwarm')
plt.title('Correlation Matrix')
plt.tight_layout()
plt.show()

# Pairplot of key features vs mpg
key_cols = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration']
sns.pairplot(df[key_cols], plot_kws={'alpha': 0.4})
plt.suptitle('Pairplot of Key Features', y=1.02)
plt.show()

X = df.drop(columns=['mpg'])
y = df['mpg']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train: {X_train.shape}, Test: {X_test.shape}")

# Preprocessing steps: impute missing values, then scale
preprocessor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Linear Regression Pipeline
lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])
lr_pipeline

def evaluate(name, pipeline, X_train, y_train, X_test, y_test):
    pipeline.fit(X_train, y_train)
    preds = pipeline.predict(X_test)
    mae  = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2   = r2_score(y_test, preds)
    print(f"{'='*40}")
    print(f"Model : {name}")
    print(f"MAE   : {mae:.3f}")
    print(f"RMSE  : {rmse:.3f}")
    print(f"R²    : {r2:.3f}")
    return preds

lr_preds = evaluate('Linear Regression', lr_pipeline, X_train, y_train, X_test, y_test)

import matplotlib.pyplot as plt

# 1. Fit and Predict using only the Linear Regression pipeline
lr_pipeline.fit(X_train, y_train)
preds = lr_pipeline.predict(X_test)
r2_score = lr_pipeline.score(X_test, y_test)

# 2. Create the plot
plt.figure(figsize=(8, 6))
plt.scatter(y_test, preds, alpha=0.6, edgecolors='k', linewidths=0.5, color='royalblue')

# 3. Draw the "Perfect Prediction" line
# This represents where the dots would be if the model was 100% accurate
lims = [min(y_test.min(), preds.min()), max(y_test.max(), preds.max())]
plt.plot(lims, lims, 'r--', lw=2, label='Perfect Fit')

# 4. Labels, Title (with R²), and Legend
plt.xlabel('Actual MPG')
plt.ylabel('Predicted MPG')
plt.title(f'Linear Regression Analysis\n$R^2$ Score: {r2_score:.3f}')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5) # Added a light grid for better readability

plt.tight_layout()
plt.show()

import joblib
from sklearn.metrics import r2_score

# 1. Fit and Predict using only the Linear Regression pipeline
lr_pipeline.fit(X_train, y_train)
preds = lr_pipeline.predict(X_test)

# 2. Evaluate performance
score = r2_score(y_test, preds)

# 3. Save the model to a file
joblib.dump(lr_pipeline, 'linear_regression_model.pkl')

print("Linear Regression Analysis Complete")
print("-" * 30)
print(f"R² Score: {score:.4f}")
print("Model saved to: linear_regression_model.pkl")

